version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "9010:8000"  # 👈 Host:Container (9010 externally, 8000 inside)
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`j4swo8cocwsgwkg48o08w4ww.dev.faircloud.ai`)
      - traefik.http.services.fastapi.loadbalancer.server.port=8000



